### ISSUE TITLE
0-Leistung bei Offline

### ISSUE THREAD

**Issue by FMainz** [thonhaus/deye2mqtt#1]
Hallo,

ich habe bei mir eine Änderung an deinem Script durchgeführt. Hintergrund ist, wenn der deye-WR offline ist, werden auch keine Leistungsdaten an den Broker gesendet. Für meine Anzeige im VenusOS von Victron benötige ich aber in regelmässigen Abständen einen Leistungswert, sonst verschwindet das "PV-Wechselrichter"-Symbol in der Anzeige.

Mit dieser kleinen Änderung beseitige ich das Problem:
```
    else
        send_lwt Offline
        send_msg current_power 0
    fi
```

Cool wäre auch, wenn man in der config einstellen könnte, ob der Topic RAW oder als JSON gesendet werden soll.
Falls du das nicht machen möchtest, baue ich mir das bei passender Gelegenheit selbst.

Gruß Frank

**Comment by thonhaus** [comment]
current_power 0 wird nun geschickt, wenn der Wechselrichter offline ist. Topic als JSON senden werde ich nicht mehr einbauen, da ich selbst auf einen anderen Wechselrichter umgestiegen bin. Du kannst gerne einen pr dazu machen.
